albums/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.AlbumListView.as_view(), name="album_list"),
    url(r'^(?P<id>\d+)/$', views.AlbumDetailview.as_view(), name="album_details"),
]

artists/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.artist_list, name="artist_list"),
    url(r'^(?P<id>\d+)/$', views.artist_detail, name="artist_detail"),
    url(r'^(?P<id>\d+)/edit/$', views.artist_edit, name="artist_edit"),
    url(r'^new/$', views.artist_new, name="artist_new"),
]

core/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
]

music/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^artists/', include ("artists.urls", namespace="artists")),
    url(r'^', include('core.urls', namespace="core")),
    url(r'^albums/', include ("albums.urls", namespace="albums"))
]

albums/models.py
from django.db import models
from django.core.urlresolvers import reverse
from datetime import datetime

class Album(models.Model):
    album_name = models.CharField(max_length=250)
    artist_name = models.CharField(max_length=250)
    collection_or_greatest_hits = models.CharField(max_length=8)
    studio_or_live = models.CharField(max_length=8)
    year_released = models.CharField(max_length=4)
    default='draft'

    class Meta:
         ordering = ['artist_name', 'album_name', 'collection_or_greatest_hits', 'studio_or_live', 'year_released']
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse("album:album_list", kwargs={self.pk})

artists/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Artist (models.Model):
    #artist name
    name = models.CharField(max_length = 40)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("artists:artist_detail", kwargs={"id":self.pk})

core/models.py
from django.db import models

# Create your models here.

songs/models.py
from django.db import models

class Song (models.Model):
    name = models.CharField(max_length=100)
    length = models.DurationField()
    track_number = models.IntegerField()
    artists = models.ManyToManyField("artists.Artist")

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_artist_names(self):
        artist_names = [artist.name for artist in self.artists.all()]
        return ", ".join(artist_names)

albums/forms.py
from django import forms

from .models import Album

class AlbumForm(forms.ModelForm):

    class Meta:
        model = Album
        fields = ("album_name",)
        model = Album
        fields = ("album_name")
        model = Album
        fields = ("collection_or_greatest_hits")
        model = Album
        fields = ("studio_or_live")
        model = Album
        fields = ("year_released")

    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["album_name"].widget.attrs.update({
            "class":"form-control",

        self.fields["album_name"].widget.attrs.update({
            "class":"form-control",

        self.fields["collection_or_greatest_hits"].widget.attrs.update({
            "class":"form-control",

        self.fields["studio_or_live"].widget.attrs.update({
            "class":"form-control",

        self.fields"year_released"].widget.attrs.update({
            "class":"form-control",
        })

artists/forms.py
from django import forms

from .models import Artist

class ArtistForm(forms.ModelForm):
  
    class Meta:
        model = Artist
        fields = ("name",)

    def __init__ (self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["name"].widget.attrs.update({
            "class":"form-control",
        })

albums/views.py
from django.shortcuts import render, get_object_or_404
from django.core.urlresolvers import reverse
from . models import Album
from django.http import HttpResponse


def album_list(request):
    albums = Album.objects.all()

    context = {
        "albums":album_list

    }

    return render(request, "albums/album_list.html", context)


def album_details(request):
    album = get_object_or_404(Album, pk=id)

    context = {
        "album": album

    }

    return render(request, "albums/album_details.html", context)

artists/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.core.urlresolvers import reverse
from django.db.models import Q

from .models import Artist
from .forms import ArtistForm


def artist_list(request):

    artists = Artist.objects.all()

    query = request.GET.get("q")
    if query:
        artists = artists.filter(
            Q(name__icontains=query)
        )
        artists = artists.distinct()

    context = {
        "artists": artists,
    }
    # return HttpResponse("Here be I.")
    return render (request, "artists/index.html", context)


def artist_detail(request, id):
    artist = get_object_or_404(Artist, pk=id)

    context = {
        "artist": artist,
    }

    # return HttpResponse("Here are the artists")
    return render (request, "artists/artist_detail.html", context)


def artist_new(request):
    if request.method == "POST":
        form = ArtistForm(request.POST)
        if form.is_valid():
            artist = form.save()
            messages.success(request, "Artist added!")
            return redirect("artists:artist_detail", id=artist.pk)
    else: 
        form = ArtistForm()

    context = {
        "form":form,
    }

    return render(request, "artists/artist_edit.html", context)


def artist_edit(request, id):
    artist = get_object_or_404(Artist, pk=id)

    if request.method == "POST":
        form = ArtistForm(request.POST, instance=artist)
        if form.is_valid():
            artist=form.save()
            messages.success(request, "Artist updated!")
            return redirect("artists:artist_detail", id=artist.pk)

    else:
        form = ArtistForm(instance=artist)

    context = {
        "form": form,
        "artist": artist,
    }

    return render(request, "artists/artist_edit.html", context)

core/views.py
from django.shortcuts import render
from django.http import HttpResponse



def index(request):
    # return HttpResponse("Howdy")
    return render(request, "core/index.html")

songs/views.py
from django.shortcuts import render

# Create your views here.

albums/templates/albums/album_list.html
{% extends "core/base.html" %}

{% block content %}
    <h2>hello world </h2>

{% for album in albums %}

    {{ album }}

{% endfor %}

{% endblock content %}

albums/templates/albums/index.html
{% extends "core/base.html" %}

{% block content %}
    <div class = "information_list">
        <h1>
            Albums
        </h1>
       
        <hr>

        {% if album %}
            {% for album in albums %}
                {% include "album/_album_thumbnail.html" %}
            {% endfor %}
        {% else %}
            <p>No Albums found.</p>
        {% endif %}
      
        <hr>
        
       
    </div>

{% endblock content %}

artists/templates/artists/_artist_thumbnail.html
<div class=" artist-thumbnail">
    <div class="caption">
        <h4>
            <a href="{{artist.get_absolute_url}}">
                {{artist.name}}
            </a>
        </h4>
    </div>
</div>

artists/templates/artists/artist_detail.html
{% extends "core/base.html" %}

{% block content %}
    <div class="information_list">
        <h2>
            <div class="pull-right">
                <a href="{% url 'artists:artist_edit' artist.pk %}">
                    <i class="fa fa-pencil-square"></i>
                </a>
            </div>
            
            {{artist.name}}
            <hr>
        </h2>        
    </div>
{% endblock content %}      

artists/templates/artists/artist_edit.html
{% extends "core/base.html" %}

{% block content %}
    {% if artist %}
        <h2>Edit: {{artist.name}}</h2>
    {% else %}
        <h2>New Artist</h2>
    {% endif %}
    
    <form action="" method = "POST" class="input_form">
        {% csrf_token %}
  
        {% for field in form %}
            {% include "core/_form_input.html" %}
        {% endfor %}

        <button type="submit" class="btn btn-primary btn-block save_button">
            Save
        </button>
    </form>

{% endblock content %}

artists/templates/artists/index.html
{% extends "core/base.html" %}

{% block content %}
    <div class = "information_list">
        <h1>
            Artists
        </h1>
       
        <hr>

        {% if artists %}
            {% for artist in artists %}
                {% include "artists/_artist_thumbnail.html" %}
            {% endfor %}
        {% else %}
            <p>No artists found.</p>
        {% endif %}
      
        <hr>
        
        <div class="input_form">
            <a href="{% url 'artists:artist_new' %}" class="btn btn-primary btn-block">
                Add a new artist.
            </a>            
        </div>

    </div>

{% endblock content %}

core/templates/core/_form_input.html
<div 
    {% if field.errors %}
        class="form-group has-error"
    {% else %}
        class="form-group"
    {% endif %}
>  
    {{field.label_tag}}
    {{field}}

    {% if field.errors %}
        <span class="help-block">
        {% for error in field.errors %}
            {{error}}
        {% endfor %}
</div>
{% endif %}

core/templates/core/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>
        {% block title %}
            Music Library
        {% endblock title %}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <script src="https://use.fontawesome.com/a04d9e4c1c.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'core/styles.css' %}" />
</head>
<body>
    <header>
        <nav class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">

               <button 
                    type = "button"
                    class ="navbar-toggle collapsed"
                    data-toggle="collapse"
                    data-target="#header-navbar-collapse"
                >
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>                    
                </button>
         
                <a href="{% url 'core:index' %}" class="navbar-brand">
                    Music Library
                </a>
            </div>
          
            <div id="header-navbar-collapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="/artists">Artists</a>
                    </li>
                    <li>
                        <a href="/albums">Albums</a>
                    </li>
                    <li>
                        <a href="#">Songs</a>
                    </li>
                </ul>      
            </div>

          </div><!-- end container -->
        </nav>
    </header>

    <div class="container">
        <div class="content">
            {% block content %}

            {% endblock %}
        </div>
    </div>
    
    <footer class="page-footer">
        <hr>
        <div class="container">
            &copy; Spatial Gallon 2016
        </div>
    </footer>

    <script   src="https://code.jquery.com/jquery-3.1.0.min.js"   integrity="sha256-cCueBR6CsyA4/9szpPfrX3s49M9vUU5BgtiJj06wt/s="   crossorigin="anonymous"></script>
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/index.html
{% extends "core/base.html" %}

{% block content %}

    <h1>
        Music Library
    </h1>

    
    <div class="input_form">
        <form action="{% url 'artists:artist_list' %}">
            <label for="index-search">
                Search Library
            </label>
            <input type="text" id="index-search" class="form-control" name="q" placeholder="Find an artist.">
            <button type="submit" class="btn btn-primary btn-block">Submit</button>
        </form>                
    </div>    

    <hr>
    
    <li>
        <h2>
            <a href="/artists">Artists</a>
        </h2>
    </li>
    <li>
        <h2>
            <a href="/albums">Albums</a>
        </h2>
    </li>
    <li>
        <h2>
            <a href="/songs">Songs</a>
        </h2>
    </li>

{% endblock content %}